"""The committed frontend snapshot, checked against the schema FastAPI publishes.

``frontend/src/api/openapi.snapshot.json`` is the middle link of a three-step
drift chain::

    review_api source  --[this test]-->  openapi.snapshot.json
    openapi.snapshot.json  --[frontend contract.test.ts]-->  api/types.ts

The second link already existed: the Vitest contract test compares the
snapshot's properties against the handwritten TypeScript DTOs, so a field the
browser invents, or one it forgets, fails there. The first link did not. Until
this test, the snapshot was regenerated by hand, which means a backend change
that widened, narrowed or renamed the published contract left a stale file
behind and the Vitest test went on happily validating the browser against last
month's API.

So the failure this closes is specific: the frontend passing its own checks
while being wrong about the backend.

It lives in the Python suite rather than in frontend CI on purpose. The
authority is ``create_app().openapi()``, which needs FastAPI and Pydantic --
already installed for every other test in this package -- and the change that
invalidates the snapshot is always a *backend* change. Putting the guard where
those changes are made means the person who edits ``review_api/models.py`` is
the one whose build goes red, rather than a frontend job that happens to run
later. Node CI therefore installs no Python, and this suite installs no Node.

Building the schema is safe by construction. ``create_app()`` takes no
lifespan, so it opens no database, creates no ``storage/`` directory, starts no
server, contacts no provider, and reads no dataset or holdout split -- the same
property ``test_api_models.py`` and ``test_openapi.py`` already depend on.
``test_building_the_schema_touches_no_storage`` below asserts it rather than
assuming it, because the whole point of running this in CI is that it must
never be the thing that creates a queue file.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from review_api import create_app
from review_persistence.config import PROJECT_ROOT

# Anchored to the package layout, never to the working directory: pytest may be
# invoked from anywhere, and a CWD-relative path would silently compare against
# nothing.
SNAPSHOT_PATH = PROJECT_ROOT / "frontend" / "src" / "api" / "openapi.snapshot.json"

# The exact command that produced the committed file. Quoted in the failure
# message so a developer never has to guess the serialization, which is the one
# thing a hand-regenerated snapshot gets wrong.
REGENERATE_COMMAND = (
    'python -c "import json; from review_api import create_app; '
    'print(json.dumps(create_app().openapi(), indent=2, sort_keys=True))" '
    "> frontend/src/api/openapi.snapshot.json"
)


def render_schema() -> str:
    """Serialize the published schema the one way the snapshot is written.

    ``sort_keys`` makes the file diffable and independent of dict ordering, and
    two-space indentation matches the rest of the frontend tree. Nothing else
    is normalised: no path, method, schema, property, required list, enum value
    or status code is altered, so a real contract change always shows up.

    The trailing newline is the shell redirect's, from ``print``. It is part of
    the committed bytes, so it is part of what is compared.
    """
    schema: dict[str, Any] = create_app().openapi()
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def test_the_committed_snapshot_matches_the_published_schema() -> None:
    assert SNAPSHOT_PATH.exists(), f"Missing frontend OpenAPI snapshot at {SNAPSHOT_PATH}."

    committed = SNAPSHOT_PATH.read_text(encoding="utf-8")
    generated = render_schema()

    # Compared, never rewritten. A test that repaired the file would turn a
    # contract change into a silent one, which is the failure this exists to
    # prevent -- and in CI it would rewrite a file nobody reviews.
    assert committed == generated, (
        "frontend/src/api/openapi.snapshot.json is out of date with "
        "review_api's published schema.\n"
        "If the API change is intended, regenerate it from the repository root:\n"
        f"  {REGENERATE_COMMAND}\n"
        "Then re-check the handwritten TypeScript contract in "
        "frontend/src/api/types.ts, which is validated against this file by "
        "frontend/src/api/contract.test.ts."
    )


def test_the_snapshot_is_written_in_the_documented_form() -> None:
    """Sorted keys and two-space indent, so a diff shows meaning and not churn.

    Asserted against the committed bytes rather than against a re-serialization
    of them: a file that happens to round-trip through a different writer could
    still carry a formatting difference that makes every future diff unreadable.
    """
    committed = SNAPSHOT_PATH.read_text(encoding="utf-8")
    reparsed = json.loads(committed)

    assert committed == json.dumps(reparsed, indent=2, sort_keys=True) + "\n"


def test_building_the_schema_touches_no_storage(tmp_path: Path) -> None:
    """No database, no directory, no file -- this runs in CI on every push.

    ``configured_database_path`` is where the production lifespan would open the
    queue. Building a schema must not bring that path into existence, and the
    check is written against the real configured path rather than a patched one
    because that is the file an accident would actually create.
    """
    from review_api.dependencies import configured_database_path

    database_path = configured_database_path()
    existed_before = database_path.exists()

    render_schema()

    assert database_path.exists() is existed_before
    # Nothing was written into the test's own scratch directory either, which
    # would be the other way a stray write could hide.
    assert list(tmp_path.iterdir()) == []
